from docx import Document
import os

# Получаем путь к директории скрипта
script_dir = os.path.dirname(os.path.abspath(__file__))

# Шаблон для брони аудитории
doc1 = Document()
doc1.add_heading('СЛУЖЕБНАЯ ЗАПИСКА', 0)
doc1.add_heading('О бронировании аудитории', level=1)
doc1.add_paragraph('')
doc1.add_paragraph('Дата: _________________')
doc1.add_paragraph('')
doc1.add_paragraph('Прошу забронировать аудиторию для проведения мероприятия.')
doc1.add_paragraph('')
doc1.add_paragraph('Цель мероприятия: _________________________________')
doc1.add_paragraph('')
doc1.add_paragraph('Дата проведения: _________________________________')
doc1.add_paragraph('')
doc1.add_paragraph('Время проведения: _________________________________')
doc1.add_paragraph('')
doc1.add_paragraph('Количество участников: _________________________________')
doc1.add_paragraph('')
doc1.add_paragraph('Необходимое оборудование: _________________________________')
doc1.add_paragraph('')
doc1.add_paragraph('')
doc1.add_paragraph('Подпись: _________________')
doc1.save(os.path.join(script_dir, 'template_auditorium.docx'))
print('✅ template_auditorium.docx создан')

# Шаблон для освобождения
doc2 = Document()
doc2.add_heading('СЛУЖЕБНАЯ ЗАПИСКА', 0)
doc2.add_heading('Об освобождении от занятий', level=1)
doc2.add_paragraph('')
doc2.add_paragraph('Дата: _________________')
doc2.add_paragraph('')
doc2.add_paragraph('Прошу освободить от занятий/мероприятий.')
doc2.add_paragraph('')
doc2.add_paragraph('ФИО студента: _________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('Группа: _________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('Дата освобождения: _________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('Время: _________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('Причина освобождения: _________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('_________________________________________________________')
doc2.add_paragraph('')
doc2.add_paragraph('')
doc2.add_paragraph('Подпись студента: _________________')
doc2.add_paragraph('')
doc2.add_paragraph('Подпись руководителя: _________________')
doc2.save(os.path.join(script_dir, 'template_release.docx'))
print('✅ template_release.docx создан')

# Шаблон для пропуска
doc3 = Document()
doc3.add_heading('СЛУЖЕБНАЯ ЗАПИСКА', 0)
doc3.add_heading('О пропуске посторонних лиц', level=1)
doc3.add_paragraph('')
doc3.add_paragraph('Дата: _________________')
doc3.add_paragraph('')
doc3.add_paragraph('Прошу оформить пропуск для посторонних лиц на территорию учреждения.')
doc3.add_paragraph('')
doc3.add_paragraph('ФИО посетителя: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('Паспортные данные: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('Дата визита: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('Время визита: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('Цель визита: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('Ответственное лицо: _________________________________')
doc3.add_paragraph('')
doc3.add_paragraph('')
doc3.add_paragraph('Подпись ответственного: _________________')
doc3.save(os.path.join(script_dir, 'template_pass.docx'))
print('✅ template_pass.docx создан')

print('\n🎉 Все шаблоны успешно созданы!')
